name = "Hugo JinDo"
license = "MIT"
licenselink = "https://github.com/pcm9881/hugo-jindo/blob/main/LICENSE"
description = "Hugo theme as simple as plain book"
homepage = "https://github.com/pcm9881/hugo-jindo"
tags = ["blog", "modern"]
min_version = "0.0.1"

[author]
name = "pcm9881"
homepage = "https://github.com/pcm9881"
