baseurl = "https://pcm9881.github.io/"
title = "PCM9881"
theme = "hugo-jindo"
languageCode = "ko"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2023 pcm9881"

# Markup
[markup]
defaultMarkdownHandler = 'goldmark'

# Services
[services]

[services.googleAnalytics]
ID = "GoogleAnalytics ID"

defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false

# Languages
[languages]
[languages.ko]
languageName = "한국어"
contentDir = 'content.ko'
disabled = false
weight = 1
[[languages.ko.menus.main]]
identifier = "about"
name = '소개'
pageRef = '/about'
weight = 10
[[languages.ko.menus.main]]
identifier = "posts"
name = '포스트'
pageRef = '/posts'
weight = 20
[[languages.ko.menus.main]]
name = '카테고리'
identifier = "categories"
pageRef = '/categories'
weight = 30
[[languages.ko.menus.main]]
name = '태그'
pageRef = '/tags'
identifier = "tags"
weight = 40
[languages.en]
languageName = "English"
contentDir = 'content.en'
disabled = false
weight = 2
[[languages.en.menus.main]]
identifier = "about"
name = 'About'
pageRef = '/about'
weight = 10
[[languages.en.menus.main]]
identifier = "posts"
name = 'Posts'
pageRef = '/posts'
weight = 20
[[languages.en.menus.main]]
identifier = "categories"
name = 'Categories'
pageRef = '/categories'
weight = 30
[[languages.en.menus.main]]
identifier = "tags"
name = 'Tags'
pageRef = '/tags'
weight = 40

# Params
[params]
Favicon = "/images/favicon.ico"
Logo = "/images/logo.png"
Title = ""
TitleCategory = "image"         # or text

# Search
Search = false

# Translate
Languages = true

# Slide
Slide = true

# Slide
Toc = true

[params.author]
github = "github username"
